client_config_backend: settings
client_config:
  client_id: 1025038110742-isu0pakkl9pebeb273d58opkbqa3f6j8.apps.googleusercontent.com
  client_secret: dMqiNhciWi8v8MT8LPVyMqFF

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive